language: node_js

node_js:
  - "13"

env:
  - NODE_ENV=ci

cache:
  directories:
  - node_modules

before_install:
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install

before_script: greenkeeper-lockfile-update

script:
  - npm run type-check
  - npm run lint
  - npm run build
  - npm run build:prod
  - npm run test:no-cache -- --maxWorkers=4

after_script: greenkeeper-lockfile-upload

after_success:
  - bash <(curl -s https://codecov.io/bash)
